### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jlboba** [Mysta3/simon_app#1]
# Feedback 

Overall result: Complete! 

## Code Quality 

Code is well formatted (indentations, consistent semi-colons, explicitly named variables). Organized nicely as well by putting things in nice order (e.g. holding all your static data like all the DOM elements and the questions object towards the top). Easily readable and understandable if you take the time to read through the functions. Could use a little more organization via brief comments to explain what a certain function actually does - this also makes things much easier for you yourself to find. 

Overall, however, again really well formatted and clean code.

## Technical Requirements 

Renders in browser with no errors, separated concerns into distinct HTML, CSS and JS files. Used all of the knowledge gained from unit 1. Met MVP super early on and utilized the extra time very smartly by taking that time to refactor the code with concepts you were initially uncomfortable with, but ultimately knew more than you thought! Meets all technical requirements perfectly. 

## Creativity and Interface 

Wonderfully styled interface, and I absolutely love that you pulled in a CSS framework despite us not showing you all how to use one. It fits the theme you were going for perfectly, and I love all the sound effects you included as well - though the initial loading sound effect can be a little surprising when you have no warning. Still, everything looks great and I love your attention to detail, like the custom cursor.

## Functionality 

Works perfectly as intended! Love that you included an instructions button as well to help guide and user that might not know how to play simon. Could use some work on the mobile responsiveness, as you mentioned during the presentation, but overall works quite well!

## Presentation 

Wonderful README! Includes all the necessary details in a nice, clean and easily readable format. Love the demo gifs as well! The only thing I'll mention is the images in your Notes section seem to be broken, but beyond that,great work :)

( p.s. feel free to close the issue once you've read it! )

**Comment by Mysta3** [comment]
Thank you for the feedback!
